default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 51.15.239.209
  username: jh
  password: sheepworld

development:
  <<: *default
  database: gescoop_dev

production:
  <<: *default
  database: gescoop_prod